name: RPG
author: ImUnsmart
main: me.imunsmart.rpg.Main
version: 0.1
commands:
  giveweapon:
    description: Give a weapon item.
  givearmor:
    description: Give an armor item.
  spawnmob:
    description: Spawn a mob.
  givegems:
    description: Give a player gems.
  givescraps:
    description: Give a player scraps.
  spawner:
    description: Create a spawner.
  suicide:
    description: Kill a player.