name: RPG
author: ImUnsmart
main: Main
version: BETA
depend: [dynmap]
api-version: 1.13
commands:
  giveweapon:
    description: Give a weapon item.
  givearmor:
    description: Give an armor item.
  spawnmob:
    description: Spawn a mob.
  givegems:
    description: Give a player gems.
  givescraps:
    description: Give a player scraps.
  giveitem:
    description: Give a specialized item.
  givetool:
    description: Give a specialized tool.
  spawner:
    description: Create a spawner.
  suicide:
    description: Kill a player.
  broadcast:
    description: Yell something.
    aliases: [bc]
  gmc:
    description: Change gamemode to creative.
  gma:
    description: Change gamemode to survival.
  gms:
    description: Change gamemode to adventure.
  gmsp:
    description: Change gamemode to spectator.
  kick:
    description: Kick a player.
  ban:
    description: Ban a player.
  ban-ip:
    description: Ban an IP.
  tempban:
    description: Ban a player temporarily.
  stats:
    description: Modify stats.
  inventory:
    description: Open an inventory.
    aliases: [inv]
  givetools:
    description: Gives tools.
  warp:
    description: Warp places.
  speed:
    description: Change fly speed
  fly:
    description: Toggle fly ability.
  re:
    description: Remove entities that shouldn't be there.
  quests:
    description: View a list of quests.
    aliases: [q]